### ISSUE TITLE
Can I add my own config?

### ISSUE THREAD

**Issue by Alecto** [1000ch/postcss-csscomb#1]
I used gulp-csscomb, it was possible to use my own .csscomb.json there. 
Now I want to go to postcss plugins, found your plugin. 

I tried using let options = {} - it works, but it turns out very cumbersome.

Is it possible to use my own json file in it?

And another question, the plugin has not been updated for several years, is it relevant? because many plugins are not supported by the authors. Thanks for the help.

**Comment by 1000ch** [comment]
Does it mean this plugin can include such functionality? It technically can, but should be out of scope.

You can have your own config as JSON file and load it anywhere to pass as the argument of this plugin.

> the plugin has not been updated for several years, is it relevant?

This plugin is maintained, but [CSSComb](https://github.com/csscomb/csscomb.js) seems not to be maintained actively. Then, [`stylelint`](https://github.com/stylelint/stylelint) can be another solution.
