### ISSUE TITLE
postcss-csscomb conflicts with gulp-sourcemaps

### ISSUE THREAD

**Issue by Alecto** [1000ch/postcss-csscomb#2]
const plugins = [
    $.csscomb('yandex')
];

.pipe($.sourcemaps.init())
    .pipe($.postcss(plugins))
.pipe($.sourcemaps.write())

as a result, wrong file paths.

**Comment by 1000ch** [comment]
`postcss-csscomb` does not treat file paths, only touches actual css data [as you can see](https://github.com/1000ch/postcss-csscomb/blob/main/index.js).
